import { Link, router, usePage } from '@inertiajs/react';
import { ArrowLeft, BookOpen, CheckCircle2, ClipboardList, FilePlus2, GraduationCap, Users } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import ProfessionalLayout from '@/Layouts/ProfessionalLayout';
import { formatNumber } from '@/lib/format';
import type { PageProps } from '@/types';

interface InstructorCourse { id: number; title: string; slug: string; thumbnail?: string | null; is_published: boolean; students_count: number; lessons_count: number; enrollments_count: number; rating_avg: number; }
interface Learner { id: number; name?: string; course?: string; progress_percent: number; status: string; }
interface SubmissionItem { id: number; student?: string; title?: string; course?: string; content?: string | null; attachment_url?: string | null; status: string; score?: number | null; max_score: number; feedback?: string | null; submitted_at?: string | null; }

export default function InstructorDashboard() {
    const { profile, stats, courses, learners, submissions = [] } = usePage<PageProps & { profile: { name: string; avatar?: string | null; bio?: string | null; instructor?: { specialty?: string | null; experience_years?: number | null } | null }; stats: { courses: number; published_courses: number; learners: number; lessons: number; pending_submissions?: number }; courses: InstructorCourse[]; learners: Learner[]; submissions?: SubmissionItem[] }>().props;
    const [scores, setScores] = useState<Record<number, string>>({});
    const [feedbacks, setFeedbacks] = useState<Record<number, string>>({});
    return <ProfessionalLayout role="instructor"><div className="mx-auto flex max-w-7xl flex-col gap-7">
        <section className="relative overflow-hidden rounded-[2rem] bg-deep-gradient p-7 text-white shadow-lift md:p-9"><div className="pointer-events-none absolute -left-20 -top-20 size-72 rounded-full bg-brand-400/20 blur-3xl" /><div className="relative flex flex-wrap items-end justify-between gap-6"><div><span className="text-xs font-bold text-brand-200">فضای کار مدرس</span><h2 className="mt-3 text-3xl font-black">سلام {profile.name}، آماده ساختن یک تجربه یادگیری تازه‌ای؟</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/65">دوره‌ها، محتوای آموزشی و پیشرفت یادگیرندگان را از یک فضای متمرکز مدیریت کنید.</p></div><Link href="/admin/courses/create" className="inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-black text-deep-green hover:bg-brand-100"><FilePlus2 className="size-4" /> ایجاد دوره جدید</Link></div></section>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[{ label: 'دوره‌ها', value: stats.courses, icon: BookOpen }, { label: 'دوره‌های منتشرشده', value: stats.published_courses, icon: CheckCircle2 }, { label: 'یادگیرندگان', value: stats.learners, icon: Users }, { label: 'درس‌های آموزشی', value: stats.lessons, icon: GraduationCap }, { label: 'تکلیف در انتظار', value: stats.pending_submissions ?? 0, icon: ClipboardList }].map((item) => <div key={item.label} className="flex items-center gap-4 rounded-2xl border border-white/80 bg-white/80 p-5 shadow-soft"><span className="panel-stat-icon"><item.icon className="size-5" /></span><div><strong className="block text-2xl font-black text-navy">{formatNumber(item.value)}</strong><span className="text-xs font-bold text-navy/45">{item.label}</span></div></div>)}</section>
        <section id="courses" className="scroll-mt-24"><div className="mb-4 flex items-center justify-between"><div><div className="dashboard-eyebrow"><span /> استودیو محتوا</div><h2 className="mt-2 text-xl font-black text-navy">دوره‌های شما</h2></div><Link href="/admin/courses" className="text-xs font-bold text-brand-700">مدیریت کامل دوره‌ها ←</Link></div><div className="grid gap-5 md:grid-cols-2">{courses.length > 0 ? courses.map((course) => <Link key={course.id} href={`/admin/courses/${course.id}/edit`} className="group flex gap-4 rounded-2xl border border-white/80 bg-white/80 p-4 shadow-soft transition-all hover:-translate-y-1"><div className="flex size-24 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-brand-100 text-brand-600">{course.thumbnail ? <img src={course.thumbnail} alt={course.title} className="size-full object-cover" /> : <BookOpen className="size-8" />}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="line-clamp-2 text-sm font-black leading-6 text-navy group-hover:text-brand-700">{course.title}</h3><span className={`shrink-0 rounded-lg px-2 py-1 text-[0.62rem] font-black ${course.is_published ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{course.is_published ? 'منتشر' : 'پیش‌نویس'}</span></div><div className="mt-4 flex flex-wrap gap-4 text-xs font-bold text-navy/45"><span>{formatNumber(course.lessons_count)} درس</span><span>{formatNumber(course.enrollments_count)} ثبت‌نام</span><span>امتیاز {formatNumber(course.rating_avg)}</span></div></div><ArrowLeft className="mt-1 size-4 shrink-0 text-navy/25" /></Link>) : <div className="col-span-full rounded-2xl border border-dashed border-brand-200 bg-white/55 p-10 text-center"><BookOpen className="mx-auto size-8 text-brand-500" /><p className="mt-3 text-sm font-bold text-navy/55">هنوز دوره‌ای برای شما ثبت نشده است.</p><Link href="/admin/courses/create" className="mt-3 inline-block text-xs font-black text-brand-700">ایجاد اولین دوره ←</Link></div>}</div></section>
        <section id="learners" className="scroll-mt-24"><div className="mb-4 flex items-center justify-between"><div><div className="dashboard-eyebrow"><span /> جامعه یادگیری</div><h2 className="mt-2 text-xl font-black text-navy">آخرین یادگیرندگان</h2></div><Users className="size-5 text-brand-600" /></div><div className="overflow-x-auto rounded-2xl border border-white/80 bg-white/80 shadow-soft"><table className="w-full min-w-[34rem] text-right text-sm"><thead className="border-b border-navy/5 text-xs text-navy/40"><tr><th className="px-5 py-4">یادگیرنده</th><th className="px-5 py-4">دوره</th><th className="px-5 py-4">پیشرفت</th><th className="px-5 py-4">وضعیت</th></tr></thead><tbody>{learners.length > 0 ? learners.map((learner) => <tr key={learner.id} className="border-b border-navy/5 last:border-0"><td className="px-5 py-4 font-black text-navy">{learner.name}</td><td className="px-5 py-4 text-xs text-navy/55">{learner.course}</td><td className="px-5 py-4"><div className="flex items-center gap-2"><div className="h-2 w-24 overflow-hidden rounded-full bg-navy/5"><span className="block h-full rounded-full bg-brand-500" style={{ width: `${learner.progress_percent}%` }} /></div><span className="text-xs font-black text-brand-700">{formatNumber(learner.progress_percent)}٪</span></div></td><td className="px-5 py-4 text-xs font-bold text-brand-700">{learner.status === 'completed' ? 'تکمیل شده' : 'فعال'}</td></tr>) : <tr><td colSpan={4} className="px-5 py-10 text-center text-sm font-bold text-navy/40">هنوز یادگیرنده‌ای ثبت‌نام نکرده است.</td></tr>}</tbody></table></div></section>
    </div></ProfessionalLayout>;
}

InstructorDashboard.layout = (page: ReactNode) => page;
