import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Head, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, CheckCircle2, ClipboardList, Sparkles } from 'lucide-react';
export default function SurveyShow() {
    const { survey, questions, answers: initialAnswers, registered, registrationRequired, registrationAfter, completed, totalQuestions, errors } = usePage().props;
    // Build answers record from initial data
    const initial = {};
    for (const q of questions) {
        initial[String(q.id)] = initialAnswers[String(q.id)] ?? '';
    }
    const form = useForm({ answers: initial });
    const answeredCount = Object.values(form.data.answers).filter((v) => v !== '' && v !== null && !(Array.isArray(v) && v.length === 0)).length;
    const progress = Math.min(100, Math.round((answeredCount / Math.max(1, questions.length)) * 100));
    const input = 'w-full rounded-xl border border-navy/10 bg-white px-4 py-3 text-sm text-navy outline-none transition-colors focus:border-brand-500 focus:ring-2 focus:ring-brand-200';
    const submit = (event) => {
        event.preventDefault();
        form.post(window.location.pathname.replace(/\/$/, '') + '/answer', { preserveScroll: true });
    };
    return _jsxs("div", { dir: "rtl", className: "min-h-screen bg-soft-gray px-4 py-8 md:px-6", children: [_jsx(Head, { title: survey.title }), _jsxs("main", { className: "mx-auto flex w-full max-w-3xl flex-col gap-5", children: [_jsxs("header", { className: "flex items-center justify-between rounded-2xl bg-white px-5 py-4 shadow-soft ring-1 ring-navy/5", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "flex size-10 items-center justify-center rounded-xl bg-brand-100 text-brand-700", children: _jsx(ClipboardList, { className: "size-5" }) }), _jsxs("div", { children: [_jsx("div", { className: "text-[0.65rem] font-black text-brand-700", children: "\u0646\u0638\u0631\u0633\u0646\u062C\u06CC \u062E\u0635\u0648\u0635\u06CC" }), _jsx("h1", { className: "text-sm font-black text-navy", children: survey.title })] })] }), _jsxs("a", { href: "/", className: "inline-flex items-center gap-1 text-xs font-bold text-navy/45 hover:text-brand-700", children: ["\u0648\u0631\u0648\u062F \u0628\u0647 \u0633\u0627\u06CC\u062A ", _jsx(ArrowLeft, { className: "size-3.5" })] })] }), _jsxs("section", { className: "relative overflow-hidden rounded-[2rem] bg-deep-gradient p-6 text-white shadow-lift md:p-9", children: [_jsx("div", { className: "pointer-events-none absolute -left-16 -top-16 size-64 rounded-full bg-brand-400/20 blur-3xl" }), _jsxs("div", { className: "relative", children: [_jsxs("div", { className: "flex items-center gap-2 text-xs font-black text-brand-200", children: [_jsx(Sparkles, { className: "size-4" }), " \u062F\u06CC\u062F\u06AF\u0627\u0647 \u0634\u0645\u0627 \u0628\u0631\u0627\u06CC \u0645\u0627 \u0645\u0647\u0645 \u0627\u0633\u062A"] }), _jsx("h2", { className: "mt-3 text-2xl font-black leading-relaxed md:text-3xl", children: survey.title }), survey.description && _jsx("p", { className: "mt-3 text-sm leading-8 text-white/65", children: survey.description }), survey.welcome_message && _jsx("p", { className: "mt-4 rounded-xl border border-white/10 bg-white/5 p-3 text-sm leading-7 text-white/80", children: survey.welcome_message })] })] }), completed ? _jsxs("section", { className: "rounded-[2rem] bg-white p-8 text-center shadow-soft ring-1 ring-navy/5 md:p-12", children: [_jsx(CheckCircle2, { className: "mx-auto size-16 text-emerald-500" }), _jsx("h2", { className: "mt-5 text-2xl font-black text-navy", children: "\u0646\u0638\u0631\u0633\u0646\u062C\u06CC \u062A\u06A9\u0645\u06CC\u0644 \u0634\u062F" }), _jsx("p", { className: "mx-auto mt-3 max-w-lg text-sm leading-8 text-navy/55", children: survey.completion_message }), survey.completion_redirect && _jsxs("a", { href: survey.completion_redirect, className: "mt-6 inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-3 text-sm font-black text-white hover:bg-brand-700", children: ["\u0627\u062F\u0627\u0645\u0647 \u062F\u0631 \u0633\u0627\u06CC\u062A ", _jsx(ArrowLeft, { className: "size-4" })] })] })
                        : questions.length > 0 ? _jsxs("form", { onSubmit: submit, className: "flex flex-col gap-5", children: [survey.show_progress && _jsxs("section", { className: "rounded-2xl bg-white p-5 shadow-soft ring-1 ring-navy/5", children: [_jsxs("div", { className: "flex items-center justify-between text-xs font-black text-navy/50", children: [_jsx("span", { children: registrationRequired ? 'مرحله اول از دو مرحله' : 'پیشرفت پاسخ‌گویی' }), _jsxs("span", { children: [answeredCount, " \u0627\u0632 ", questions.length, " \u067E\u0627\u0633\u062E\u200C\u0634\u062F\u0647"] })] }), _jsx("div", { className: "mt-3 h-2 overflow-hidden rounded-full bg-brand-100", children: _jsx("div", { className: "h-full rounded-full bg-brand-600 transition-all", style: { width: `${progress}%` } }) })] }), questions.map((question, index) => {
                                    const value = form.data.answers[String(question.id)] ?? '';
                                    const setAnswer = (v) => form.setData('answers', { ...form.data.answers, [String(question.id)]: v });
                                    const fieldError = errors?.[`answers.${question.id}`];
                                    return _jsx("section", { className: "rounded-2xl bg-white p-5 shadow-soft ring-1 ring-navy/5 md:p-6", children: _jsxs("div", { className: "flex gap-3", children: [_jsx("span", { className: "flex size-8 shrink-0 items-center justify-center rounded-lg bg-brand-100 text-xs font-black text-brand-700", children: index + 1 }), _jsxs("div", { className: "flex-1", children: [_jsxs("h3", { className: "text-sm font-black leading-7 text-navy md:text-base", children: [question.title, " ", question.required && _jsx("span", { className: "text-red-500", children: "*" })] }), question.description && _jsx("p", { className: "mt-1 text-xs leading-6 text-navy/45", children: question.description }), _jsx("div", { className: "mt-4", children: renderAnswer(question, value, setAnswer, input) }), fieldError && _jsx("p", { className: "mt-2 rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-600", children: fieldError })] })] }) }, question.id);
                                }), _jsxs("button", { type: "submit", disabled: form.processing, className: "inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-l from-brand-600 to-brand-500 px-7 py-4 text-base font-black text-white shadow-glow transition-all hover:from-brand-700 hover:to-brand-600 disabled:cursor-not-allowed disabled:opacity-50", children: [form.processing ? _jsx("span", { className: "size-5 animate-spin rounded-full border-2 border-white/40 border-t-white" }) : _jsx(CheckCircle2, { className: "size-5" }), form.processing ? 'در حال ذخیره...' : 'ثبت و پایان نظرسنجی'] })] }) : _jsx("section", { className: "rounded-2xl bg-white p-8 text-center text-sm font-bold text-navy/50 shadow-soft ring-1 ring-navy/5", children: "\u0633\u0624\u0627\u0644\u06CC \u0628\u0631\u0627\u06CC \u0646\u0645\u0627\u06CC\u0634 \u0648\u062C\u0648\u062F \u0646\u062F\u0627\u0631\u062F." }), _jsx("footer", { className: "text-center text-[0.68rem] font-bold text-navy/35", children: "\u0627\u06CC\u0646 \u0646\u0638\u0631\u0633\u0646\u062C\u06CC \u0627\u0632 \u0637\u0631\u06CC\u0642 \u06CC\u06A9 \u0644\u06CC\u0646\u06A9 \u062E\u0635\u0648\u0635\u06CC \u0627\u0631\u0633\u0627\u0644 \u0634\u062F\u0647 \u0627\u0633\u062A." })] })] });
}
function renderAnswer(question, value, onChange, input) {
    const options = question.type === 'yes_no' ? ['بله', 'خیر'] : question.options;
    if (['single', 'yes_no'].includes(question.type)) {
        return _jsx("div", { className: "flex flex-col gap-2", children: options.map((option) => _jsxs("label", { className: "flex cursor-pointer items-center gap-3 rounded-xl border border-navy/10 px-4 py-3 text-sm font-bold text-navy/70 hover:border-brand-300 hover:bg-brand-50", children: [_jsx("input", { type: "radio", name: `question-${question.id}`, checked: String(value ?? '') === option, onChange: () => onChange(option), className: "size-4 border-navy/20 text-brand-600 focus:ring-brand-500" }), option] }, option)) });
    }
    if (question.type === 'multiple') {
        return _jsx("div", { className: "flex flex-col gap-2", children: options.map((option) => { const selected = Array.isArray(value) && value.includes(option); return _jsxs("label", { className: "flex cursor-pointer items-center gap-3 rounded-xl border border-navy/10 px-4 py-3 text-sm font-bold text-navy/70 hover:border-brand-300 hover:bg-brand-50", children: [_jsx("input", { type: "checkbox", checked: selected, onChange: (e) => onChange(e.target.checked ? [...(Array.isArray(value) ? value : []), option] : (Array.isArray(value) ? value.filter((item) => item !== option) : [])), className: "size-4 rounded border-navy/20 text-brand-600 focus:ring-brand-500" }), option] }, option); }) });
    }
    if (question.type === 'textarea')
        return _jsx("textarea", { rows: 5, value: String(value ?? ''), onChange: (e) => onChange(e.target.value), className: `${input} resize-y` });
    if (question.type === 'number')
        return _jsx("input", { type: "number", min: "0", value: String(value ?? ''), onChange: (e) => onChange(e.target.value), className: input });
    if (question.type === 'rating') {
        return _jsx("div", { className: "flex flex-wrap gap-2", children: [1, 2, 3, 4, 5].map((rating) => _jsx("button", { type: "button", onClick: () => onChange(rating), className: `flex size-11 items-center justify-center rounded-xl border text-sm font-black ${Number(value) === rating ? 'border-brand-600 bg-brand-600 text-white' : 'border-navy/10 bg-white text-navy/60 hover:border-brand-300'}`, children: rating }, rating)) });
    }
    return _jsx("input", { value: String(value ?? ''), onChange: (e) => onChange(e.target.value), className: input });
}
