import { Link, router, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, FileText, Trash2, Users } from 'lucide-react';
import type { ReactNode } from 'react';
import ProfessionalLayout from '@/Layouts/ProfessionalLayout';
import { formatDate, formatDuration, formatNumber } from '@/lib/format';
import type { PageProps } from '@/types';

interface Session { id: number; scheduled_at?: string | null; student?: string; status: string; duration_minutes: number; meeting_link?: string | null; report?: string | null; order_status?: string | null; }
interface Goal { id: number; title: string; student?: string; student_id: number; status: string; due_date?: string | null; total_tasks: number; completed_tasks: number; }
interface StudentOption { id: number; name: string; }
interface Slot { id: number; date?: string | null; start_time: string; end_time: string; is_booked: boolean; }

export default function CoachDashboard() {
    const { profile, stats, sessions, goals, students = [], availability = [] } = usePage<PageProps & { profile: { name: string; avatar?: string | null; bio?: string | null; coach?: { specialty?: string | null; experience_years?: number | null; rating?: number | null; is_available?: boolean } | null }; stats: { students: number; upcoming_sessions: number; completed_sessions: number; active_goals: number }; sessions: Session[]; goals: Goal[]; students?: StudentOption[]; availability?: Slot[] }>().props;
<<<<<<< Updated upstream
    const goalForm = useForm({ student_id: students[0]?.id ?? '', title: '', due_date: '' });
    const taskForm = useForm({ goal_id: goals[0]?.id ?? '', title: '' });
=======
    const goalForm = useForm({ student_id: String(students[0]?.id ?? ''), title: '', due_date: '' });
    const taskForm = useForm({ goal_id: String(goals[0]?.id ?? ''), title: '' });
>>>>>>> Stashed changes
    const slotForm = useForm({ available_date: '', start_time: '10:00', end_time: '11:00', repeat_weeks: 1 });

    return <ProfessionalLayout role="coach"><div className="mx-auto flex max-w-7xl flex-col gap-7">
        <section className="relative overflow-hidden rounded-[2rem] bg-deep-gradient p-7 text-white shadow-lift md:p-9"><div className="pointer-events-none absolute -left-20 -top-20 size-72 rounded-full bg-brand-400/20 blur-3xl" /><div className="relative flex flex-wrap items-end justify-between gap-6"><div><span className="text-xs font-bold text-brand-200">اتاق کوچینگ</span><h2 className="mt-3 text-3xl font-black">سلام {profile.name}، امروز چند مسیر را روشن‌تر می‌کنیم؟</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/65">جلسات، هدف‌ها و قدم بعدی هر دانش‌آموز را از یک فضای متمرکز دنبال کنید.</p></div><Link href="/coaching" className="inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-black text-deep-green hover:bg-brand-100">مشاهده صفحه کوچینگ <ArrowLeft className="size-4" /></Link></div></section>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: 'دانش‌آموزان', value: stats.students, icon: Users }, { label: 'جلسات پیش‌رو', value: stats.upcoming_sessions, icon: CalendarDays }, { label: 'جلسات تکمیل‌شده', value: stats.completed_sessions, icon: CheckCircle2 }, { label: 'هدف‌های فعال', value: stats.active_goals, icon: FileText }].map((item) => <div key={item.label} className="flex items-center gap-4 rounded-2xl border border-white/80 bg-white/80 p-5 shadow-soft"><span className="panel-stat-icon"><item.icon className="size-5" /></span><div><strong className="block text-2xl font-black text-navy">{formatNumber(item.value)}</strong><span className="text-xs font-bold text-navy/45">{item.label}</span></div></div>)}</section>
        <div className="grid gap-7 xl:grid-cols-[1.2fr_0.8fr]">
            <section id="sessions" className="scroll-mt-24"><div className="mb-4 flex items-center justify-between"><div><div className="dashboard-eyebrow"><span /> تقویم شما</div><h2 className="mt-2 text-xl font-black text-navy">جلسات کوچینگ</h2></div><CalendarDays className="size-5 text-brand-600" /></div><div className="flex flex-col gap-3">{sessions.length > 0 ? sessions.map((session) => <div key={session.id} className="flex flex-wrap items-center gap-4 rounded-2xl border border-white/80 bg-white/80 p-4 shadow-soft"><span className="panel-inline-icon flex shrink-0 flex-col items-center justify-center"><CalendarDays className="size-4" /><span className="mt-0.5 text-[0.58rem] font-black">جلسه</span></span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-black text-navy">{session.student ?? 'دانش‌آموز'}</h3><p className="mt-1 flex items-center gap-2 text-xs text-navy/45"><Clock3 className="size-3.5" />{formatDate(session.scheduled_at)} · {formatDuration(session.duration_minutes)}</p></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-[0.65rem] font-black text-emerald-700">{session.status === 'completed' ? 'تکمیل شده' : session.status === 'confirmed' ? 'تأیید شده' : session.status === 'cancelled' ? 'لغو شده' : 'در انتظار'}</span>{session.meeting_link && <a href={session.meeting_link} target="_blank" rel="noreferrer" className="text-xs font-black text-brand-700">ورود به جلسه</a>}{session.order_status === 'refunded' && <span className="rounded-lg bg-amber-50 px-2 py-1 text-[0.62rem] font-black text-amber-700">بازگشت وجه</span>}{session.status !== 'cancelled' && session.status !== 'completed' && <div className="flex w-full flex-wrap gap-2"><button type="button" onClick={() => router.patch(`/panel/coach/sessions/${session.id}`, { status: 'confirmed', meeting_link: session.meeting_link, report: session.report })} className="rounded-lg bg-brand-50 px-3 py-1.5 text-[0.65rem] font-black text-brand-700">تأیید</button><button type="button" onClick={() => router.patch(`/panel/coach/sessions/${session.id}`, { status: 'completed', meeting_link: session.meeting_link, report: session.report })} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-[0.65rem] font-black text-emerald-700">اتمام</button><button type="button" onClick={() => window.confirm('لغو جلسه زمان را آزاد می‌کند و در صورت پرداخت، سفارش مسترد می‌شود.') && router.patch(`/panel/coach/sessions/${session.id}`, { status: 'cancelled', meeting_link: session.meeting_link, report: session.report })} className="rounded-lg bg-red-50 px-3 py-1.5 text-[0.65rem] font-black text-red-600">لغو و بازگشت وجه</button></div>}</div>) : <div className="rounded-2xl border border-dashed border-brand-200 bg-white/55 p-10 text-center text-sm font-bold text-navy/45">جلسه‌ای برای نمایش وجود ندارد.</div>}</div></section>
            <div className="flex flex-col gap-7">
                <section id="availability" className="scroll-mt-24">
                    <div className="mb-4"><div className="dashboard-eyebrow"><span /> زمان آزاد</div><h2 className="mt-2 text-xl font-black text-navy">تقویم رزرو</h2></div>
                    <form className="mb-4 grid gap-2 rounded-2xl border border-white/80 bg-white/80 p-4" onSubmit={(event) => { event.preventDefault(); slotForm.post('/panel/coach/availability', { preserveScroll: true, onSuccess: () => slotForm.reset('available_date') }); }}>
                        <input type="date" value={slotForm.data.available_date} onChange={(event) => slotForm.setData('available_date', event.target.value)} className="rounded-xl border border-navy/10 px-3 py-2 text-xs" />
                        <div className="grid grid-cols-2 gap-2"><input type="time" value={slotForm.data.start_time} onChange={(event) => slotForm.setData('start_time', event.target.value)} className="rounded-xl border border-navy/10 px-3 py-2 text-xs" /><input type="time" value={slotForm.data.end_time} onChange={(event) => slotForm.setData('end_time', event.target.value)} className="rounded-xl border border-navy/10 px-3 py-2 text-xs" /></div>
                        <label className="flex items-center justify-between gap-2 text-[0.7rem] font-bold text-navy/60">تکرار هفتگی
                            <input type="number" min={1} max={12} value={slotForm.data.repeat_weeks} onChange={(event) => slotForm.setData('repeat_weeks', Number(event.target.value))} className="w-20 rounded-xl border border-navy/10 px-2 py-1 text-xs" />
                        </label>
                        <button type="submit" disabled={slotForm.processing} className="rounded-xl bg-brand-600 px-3 py-2 text-xs font-black text-white">افزودن زمان</button>
                    </form>
                    <div className="flex flex-col gap-2">{availability.map((slot) => <div key={slot.id} className="flex items-center justify-between rounded-xl bg-white/80 px-3 py-2 text-xs font-bold text-navy/70"><span>{slot.date} · {slot.start_time} تا {slot.end_time}</span>{slot.is_booked ? <span className="text-amber-700">رزرو شده</span> : <button type="button" onClick={() => router.delete(`/panel/coach/availability/${slot.id}`)} className="text-red-500"><Trash2 className="size-3.5" /></button>}</div>)}</div>
                </section>
                <section id="goals" className="scroll-mt-24"><div className="mb-4"><div className="dashboard-eyebrow"><span /> پیگیری رشد</div><h2 className="mt-2 text-xl font-black text-navy">هدف‌های دانش‌آموزان</h2></div>
                    {students.length > 0 && <form className="mb-4 flex flex-col gap-2 rounded-2xl border border-white/80 bg-white/80 p-4" onSubmit={(event) => { event.preventDefault(); goalForm.post('/panel/coach/goals', { preserveScroll: true, onSuccess: () => goalForm.reset('title') }); }}>
                        <select value={goalForm.data.student_id} onChange={(event) => goalForm.setData('student_id', event.target.value)} className="rounded-xl border border-navy/10 px-3 py-2 text-xs">{students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select>
                        <input value={goalForm.data.title} onChange={(event) => goalForm.setData('title', event.target.value)} placeholder="عنوان هدف" className="rounded-xl border border-navy/10 px-3 py-2 text-xs" />
                        <button type="submit" disabled={goalForm.processing} className="rounded-xl bg-brand-600 px-3 py-2 text-xs font-black text-white">ثبت هدف</button>
                    </form>}
                    <div className="flex flex-col gap-3">{goals.length > 0 ? goals.map((goal) => <div key={goal.id} className="rounded-2xl border border-white/80 bg-white/80 p-4 shadow-soft"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-black text-navy">{goal.title}</h3><p className="mt-1 text-xs text-navy/45">{goal.student} · {goal.completed_tasks}/{goal.total_tasks} تسک</p></div><button type="button" onClick={() => router.patch(`/panel/coach/goals/${goal.id}`, { status: goal.status === 'achieved' ? 'in_progress' : 'achieved' })} className="rounded-lg bg-brand-50 px-2 py-1 text-[0.62rem] font-black text-brand-700">{goal.status === 'achieved' ? 'دستاورد' : 'علامت دستاورد'}</button></div>{goal.due_date && <p className="mt-3 text-xs font-bold text-navy/40">مهلت: {formatDate(goal.due_date)}</p>}</div>) : <div className="rounded-2xl border border-dashed border-brand-200 bg-white/55 p-10 text-center text-sm font-bold text-navy/45">هدف فعالی ثبت نشده است.</div>}</div>
                    {goals.length > 0 && <form className="mt-4 flex flex-col gap-2 rounded-2xl border border-dashed border-brand-200 p-4" onSubmit={(event) => { event.preventDefault(); taskForm.post('/panel/coach/tasks', { preserveScroll: true, onSuccess: () => taskForm.reset('title') }); }}>
                        <select value={taskForm.data.goal_id} onChange={(event) => taskForm.setData('goal_id', event.target.value)} className="rounded-xl border border-navy/10 px-3 py-2 text-xs">{goals.map((goal) => <option key={goal.id} value={goal.id}>{goal.title}</option>)}</select>
                        <input value={taskForm.data.title} onChange={(event) => taskForm.setData('title', event.target.value)} placeholder="عنوان تسک" className="rounded-xl border border-navy/10 px-3 py-2 text-xs" />
                        <button type="submit" disabled={taskForm.processing} className="rounded-xl bg-navy px-3 py-2 text-xs font-black text-white">افزودن تسک</button>
                    </form>}
                </section>
            </div>
        </div>
    </div></ProfessionalLayout>;
}

CoachDashboard.layout = (page: ReactNode) => page;
