import { Link, usePage } from '@inertiajs/react';
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, FileText, Users } from 'lucide-react';
import type { ReactNode } from 'react';
import ProfessionalLayout from '@/Layouts/ProfessionalLayout';
import { formatDate, formatDuration, formatNumber } from '@/lib/format';
import type { PageProps } from '@/types';

interface Session { id: number; scheduled_at?: string | null; student?: string; status: string; duration_minutes: number; meeting_link?: string | null; report?: string | null; }
interface Goal { id: number; title: string; student?: string; status: string; due_date?: string | null; }

export default function CoachDashboard() {
    const { profile, stats, sessions, goals } = usePage<PageProps & { profile: { name: string; avatar?: string | null; bio?: string | null; coach?: { specialty?: string | null; experience_years?: number | null; rating?: number | null; is_available?: boolean } | null }; stats: { students: number; upcoming_sessions: number; completed_sessions: number; active_goals: number }; sessions: Session[]; goals: Goal[] }>().props;
    return <ProfessionalLayout role="coach"><div className="mx-auto flex max-w-7xl flex-col gap-7">
        <section className="relative overflow-hidden rounded-[2rem] bg-deep-gradient p-7 text-white shadow-lift md:p-9"><div className="pointer-events-none absolute -left-20 -top-20 size-72 rounded-full bg-brand-400/20 blur-3xl" /><div className="relative flex flex-wrap items-end justify-between gap-6"><div><span className="text-xs font-bold text-brand-200">اتاق کوچینگ</span><h2 className="mt-3 text-3xl font-black">سلام {profile.name}، امروز چند مسیر را روشن‌تر می‌کنیم؟</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/65">جلسات، هدف‌ها و قدم بعدی هر دانش‌آموز را از یک فضای متمرکز دنبال کنید.</p></div><Link href="/coaching" className="inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-black text-deep-green hover:bg-brand-100">مشاهده صفحه کوچینگ <ArrowLeft className="size-4" /></Link></div></section>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: 'دانش‌آموزان', value: stats.students, icon: Users }, { label: 'جلسات پیش‌رو', value: stats.upcoming_sessions, icon: CalendarDays }, { label: 'جلسات تکمیل‌شده', value: stats.completed_sessions, icon: CheckCircle2 }, { label: 'هدف‌های فعال', value: stats.active_goals, icon: FileText }].map((item) => <div key={item.label} className="flex items-center gap-4 rounded-2xl border border-white/80 bg-white/80 p-5 shadow-soft"><span className="panel-stat-icon"><item.icon className="size-5" /></span><div><strong className="block text-2xl font-black text-navy">{formatNumber(item.value)}</strong><span className="text-xs font-bold text-navy/45">{item.label}</span></div></div>)}</section>
        <div className="grid gap-7 xl:grid-cols-[1.2fr_0.8fr]">
            <section id="sessions" className="scroll-mt-24"><div className="mb-4 flex items-center justify-between"><div><div className="dashboard-eyebrow"><span /> تقویم شما</div><h2 className="mt-2 text-xl font-black text-navy">جلسات کوچینگ</h2></div><CalendarDays className="size-5 text-brand-600" /></div><div className="flex flex-col gap-3">{sessions.length > 0 ? sessions.map((session) => <div key={session.id} className="flex flex-wrap items-center gap-4 rounded-2xl border border-white/80 bg-white/80 p-4 shadow-soft"><span className="panel-inline-icon flex shrink-0 flex-col items-center justify-center"><CalendarDays className="size-4" /><span className="mt-0.5 text-[0.58rem] font-black">جلسه</span></span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-black text-navy">{session.student ?? 'دانش‌آموز'}</h3><p className="mt-1 flex items-center gap-2 text-xs text-navy/45"><Clock3 className="size-3.5" />{formatDate(session.scheduled_at)} · {formatDuration(session.duration_minutes)}</p></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-[0.65rem] font-black text-emerald-700">{session.status === 'completed' ? 'تکمیل شده' : session.status === 'confirmed' ? 'تأیید شده' : 'در انتظار'}</span>{session.meeting_link && <a href={session.meeting_link} target="_blank" rel="noreferrer" className="text-xs font-black text-brand-700">ورود به جلسه</a>}</div>) : <div className="rounded-2xl border border-dashed border-brand-200 bg-white/55 p-10 text-center text-sm font-bold text-navy/45">جلسه‌ای برای نمایش وجود ندارد.</div>}</div></section>
            <section id="goals" className="scroll-mt-24"><div className="mb-4 flex items-center justify-between"><div><div className="dashboard-eyebrow"><span /> پیگیری رشد</div><h2 className="mt-2 text-xl font-black text-navy">هدف‌های دانش‌آموزان</h2></div><FileText className="size-5 text-brand-600" /></div><div className="flex flex-col gap-3">{goals.length > 0 ? goals.map((goal) => <div key={goal.id} className="rounded-2xl border border-white/80 bg-white/80 p-4 shadow-soft"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-black text-navy">{goal.title}</h3><p className="mt-1 text-xs text-navy/45">{goal.student}</p></div><span className="rounded-lg bg-brand-50 px-2 py-1 text-[0.62rem] font-black text-brand-700">{goal.status === 'achieved' ? 'دستاورد' : goal.status === 'in_progress' ? 'در حال اجرا' : 'در انتظار'}</span></div>{goal.due_date && <p className="mt-3 text-xs font-bold text-navy/40">مهلت: {formatDate(goal.due_date)}</p>}</div>) : <div className="rounded-2xl border border-dashed border-brand-200 bg-white/55 p-10 text-center text-sm font-bold text-navy/45">هدف فعالی ثبت نشده است.</div>}</div></section>
        </div>
    </div></ProfessionalLayout>;
}

CoachDashboard.layout = (page: ReactNode) => page;
