import { Link, usePage } from '@inertiajs/react';
import { ArrowRight, Printer, ReceiptText } from 'lucide-react';
import type { ReactNode } from 'react';
import UserDashboardLayout from '@/Layouts/UserDashboardLayout';
import { formatDate, formatNumber, formatPrice } from '@/lib/format';
import type { PageProps } from '@/types';

interface InvoiceProps { order: { order_number: string; status: string; subtotal: number; discount: number; total: number; paid_at?: string | null; billing?: { name?: string; phone?: string; email?: string } | null; items: Array<{ title: string; quantity: number; unit_price: number; total: number }> } }
export default function Invoice() {
    const { order } = usePage<PageProps & InvoiceProps>().props;
    return <UserDashboardLayout><div className="mx-auto max-w-4xl"><div className="mb-5 flex flex-wrap items-center justify-between gap-3 print:hidden"><Link href="/dashboard/orders" className="inline-flex items-center gap-2 text-xs font-black text-brand-700"><ArrowRight className="size-4" /> سفارش‌های من</Link><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-xs font-black text-white"><Printer className="size-4" /> چاپ / ذخیره PDF</button></div><article className="rounded-3xl bg-white p-6 shadow-soft print:rounded-none print:p-0 print:shadow-none md:p-10"><header className="flex flex-wrap items-start justify-between gap-5 border-b border-navy/10 pb-6"><div><div className="flex items-center gap-2 text-brand-700"><ReceiptText className="size-5" /><span className="text-sm font-black">مرکز رشد و کارآفرینی دکتر بیدی</span></div><h1 className="mt-3 text-2xl font-black text-navy">فاکتور فروش</h1></div><div className="text-left text-xs text-navy/50"><div>شماره: <strong className="text-navy">{order.order_number}</strong></div><div className="mt-2">تاریخ پرداخت: {formatDate(order.paid_at)}</div></div></header><section className="grid gap-4 border-b border-navy/10 py-6 text-sm sm:grid-cols-2"><div><div className="text-xs font-bold text-navy/40">خریدار</div><div className="mt-1 font-black text-navy">{order.billing?.name ?? 'کاربر'}</div></div><div className="sm:text-left"><div className="text-xs font-bold text-navy/40">تماس</div><div className="mt-1 font-bold text-navy/70" dir="ltr">{order.billing?.phone ?? '—'}</div></div></section><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[32rem] text-right text-sm"><thead className="border-b border-navy/10 text-xs text-navy/45"><tr><th className="px-3 py-3">شرح</th><th className="px-3 py-3">تعداد</th><th className="px-3 py-3">قیمت واحد</th><th className="px-3 py-3">جمع</th></tr></thead><tbody>{order.items.map((item, index) => <tr key={`${item.title}-${index}`} className="border-b border-navy/5"><td className="px-3 py-4 font-bold text-navy">{item.title}</td><td className="px-3 py-4 text-navy/60">{formatNumber(item.quantity)}</td><td className="px-3 py-4 text-navy/60">{formatPrice(item.unit_price)}</td><td className="px-3 py-4 font-black text-navy">{formatPrice(item.total)}</td></tr>)}</tbody></table></div><div className="mr-auto mt-6 max-w-xs space-y-3 text-sm"><div className="flex justify-between text-navy/55"><span>جمع اولیه</span><strong>{formatPrice(order.subtotal)}</strong></div><div className="flex justify-between text-navy/55"><span>تخفیف</span><strong>{formatPrice(order.discount)}</strong></div><div className="flex justify-between border-t border-navy/10 pt-3 text-base font-black text-navy"><span>مبلغ پرداخت‌شده</span><strong className="text-brand-700">{formatPrice(order.total)}</strong></div></div></article></div></UserDashboardLayout>;
}
Invoice.layout = (page: ReactNode) => page;
