import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Clock, PlayCircle, Star, Users } from 'lucide-react';
import { Link } from '@inertiajs/react';
import { Badge } from '@/Components/ui/Badge';
import { formatDuration, formatNumber, formatPrice } from '@/lib/format';
const levelLabels = {
    beginner: 'مقدماتی',
    intermediate: 'متوسط',
    advanced: 'پیشرفته',
};
export function CourseCard({ course }) {
    const finalPrice = course.discount_price ?? course.price;
    const hasDiscount = course.discount_price !== null && course.discount_price !== undefined;
    return (_jsxs(Link, { href: `/courses/${course.slug}`, prefetch: "hover", className: "liquid-card group flex flex-col overflow-hidden transition-all duration-300 hover:-translate-y-1.5", children: [_jsx("span", { className: "liquid-blob blob-a", "aria-hidden": true }), _jsx("span", { className: "liquid-blob blob-b", "aria-hidden": true }), _jsxs("div", { className: "relative aspect-video overflow-hidden bg-gradient-to-br from-brand-100 to-emerald-50", children: [course.thumbnail ? (_jsx("img", { src: course.thumbnail, alt: course.title, loading: "lazy", decoding: "async", className: "size-full object-cover transition-transform duration-500 group-hover:scale-105" })) : (_jsx("div", { className: "flex size-full items-center justify-center text-brand-400", children: _jsx(PlayCircle, { className: "size-14 transition-transform duration-300 group-hover:scale-110" }) })), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-navy/30 to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100" }), _jsxs("div", { className: "absolute right-3 top-3 flex gap-2", children: [_jsx(Badge, { tone: "navy", children: levelLabels[course.level] ?? course.level }), hasDiscount && _jsx(Badge, { tone: "gold", children: "\u062A\u062E\u0641\u06CC\u0641" })] })] }), _jsxs("div", { className: "flex flex-1 flex-col gap-3 p-5", children: [_jsx("h3", { className: "line-clamp-2 text-base font-black leading-7 text-navy transition-colors group-hover:text-brand-700", children: course.title }), course.subtitle && (_jsx("p", { className: "line-clamp-2 text-sm leading-6 text-navy/55", children: course.subtitle })), _jsxs("div", { className: "mt-auto flex items-center gap-4 text-xs font-medium text-navy/50", children: [course.duration_minutes > 0 && (_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Clock, { className: "size-3.5" }), " ", formatDuration(course.duration_minutes)] })), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Users, { className: "size-3.5" }), " ", formatNumber(course.students_count), " \u062F\u0627\u0646\u0634\u200C\u0622\u0645\u0648\u0632"] }), course.rating_avg > 0 && (_jsxs("span", { className: "flex items-center gap-1 text-gold", children: [_jsx(Star, { className: "size-3.5 fill-gold" }), " ", formatNumber(course.rating_avg)] }))] }), _jsxs("div", { className: "flex items-end justify-between border-t border-navy/5 pt-4", children: [_jsxs("div", { className: "flex flex-col", children: [hasDiscount && (_jsx("span", { className: "text-xs text-navy/40 line-through", children: formatPrice(course.price) })), _jsx("span", { className: "text-lg font-black text-brand-700", children: formatPrice(finalPrice) })] }), _jsx("span", { className: "rounded-xl bg-brand-600 px-4 py-2 text-xs font-bold text-white shadow-glow transition-all duration-200 group-hover:bg-brand-700", children: "\u0645\u0634\u0627\u0647\u062F\u0647 \u062F\u0648\u0631\u0647" })] })] })] }));
}
