import { Link, usePage } from '@inertiajs/react';
import { CalendarDays, Clock3, MapPin, PlayCircle, Radio } from 'lucide-react';
import { router } from '@inertiajs/react';
import type { ReactNode } from 'react';
import PublicLayout from '@/Layouts/PublicLayout';
import type { PageProps } from '@/types';
import { formatDate, formatNumber } from '@/lib/format';

interface EventItem { id: number; title: string; slug: string; type: string; summary?: string; poster?: string; live_url?: string | null; event_date?: string; duration_minutes?: number; location?: string; speaker?: string; }
export default function EventsIndex() {
    const { events, filters } = usePage<PageProps & { events: { data: EventItem[]; links: unknown[]; total: number }; filters: { type: string } }>().props;
    return <div className="bg-cream"><section className="bg-deep-gradient px-4 pb-14 pt-32 text-white"><div className="container-site"><span className="text-xs font-black text-brand-200">محتوای آموزشی</span><h1 className="mt-3 text-3xl font-black md:text-5xl">وبینارها و سمینارها</h1><p className="mt-4 max-w-2xl text-sm leading-8 text-white/70">جلسه‌های آموزشی و تخصصی ما را زنده دنبال کنید یا ویدیوهای ضبط‌شده را ببینید.</p></div></section><main className="container-site py-10"><div className="mb-8 flex flex-wrap gap-2"><button type="button" onClick={() => router.get('/events')} className={`rounded-xl px-4 py-2 text-xs font-black ${!filters.type ? 'bg-deep-green text-white' : 'bg-white text-navy/60 ring-1 ring-navy/10'}`}>همه</button><button type="button" onClick={() => router.get('/events?type=webinar')} className={`rounded-xl px-4 py-2 text-xs font-black ${filters.type === 'webinar' ? 'bg-deep-green text-white' : 'bg-white text-navy/60 ring-1 ring-navy/10'}`}>وبینارها</button><button type="button" onClick={() => router.get('/events?type=seminar')} className={`rounded-xl px-4 py-2 text-xs font-black ${filters.type === 'seminar' ? 'bg-deep-green text-white' : 'bg-white text-navy/60 ring-1 ring-navy/10'}`}>سمینارها</button></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{events.data.map((event) => <Link href={`/events/${event.slug}`} key={event.id} className="group overflow-hidden rounded-3xl border border-navy/5 bg-white shadow-soft transition hover:-translate-y-1 hover:shadow-lift"><div className="relative aspect-video bg-brand-50">{event.poster ? <img src={event.poster} alt={event.title} className="size-full object-cover" /> : <div className="flex size-full items-center justify-center text-brand-500"><PlayCircle className="size-14" /></div>}<span className="absolute right-3 top-3 rounded-full bg-deep-green px-3 py-1 text-xs font-black text-white">{event.type === 'webinar' ? 'وبینار' : 'سمینار'}</span>{event.live_url && <span className="absolute left-3 top-3 inline-flex items-center gap-1 rounded-full bg-red-600 px-2.5 py-1 text-[0.65rem] font-black text-white"><Radio className="size-3" /> زنده</span>}</div><div className="p-5"><h2 className="line-clamp-2 text-lg font-black text-navy group-hover:text-brand-700">{event.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-7 text-navy/55">{event.summary}</p><div className="mt-4 flex flex-wrap gap-3 text-xs font-bold text-navy/50"><span className="flex items-center gap-1"><CalendarDays className="size-3.5" />{event.event_date ? formatDate(event.event_date) : '—'}</span>{event.duration_minutes ? <span className="flex items-center gap-1"><Clock3 className="size-3.5" />{formatNumber(event.duration_minutes)} دقیقه</span> : null}{event.location ? <span className="flex items-center gap-1"><MapPin className="size-3.5" />{event.location}</span> : null}</div></div></Link>)}</div></main></div>;
}
EventsIndex.layout = (page: ReactNode) => <PublicLayout>{page}</PublicLayout>;
