import { Link, usePage } from '@inertiajs/react';
import { ArrowRight, BarChart3, Inbox, MessageCircle, Target, Zap } from 'lucide-react';
import type { ReactNode } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import InstagramGuide from '@/Components/Admin/InstagramGuide';
import type { PageProps } from '@/types';
type Day = { day: string; total: number };
export default function InstagramAnalytics() { const { summary, byChannel, byDay } = usePage<PageProps & { summary: Record<string, number>; byChannel: Record<string, number>; byDay: Day[] }>().props; const cards = [['گفتگوها', summary.conversations, Inbox], ['کل پیام‌ها', summary.messages, MessageCircle], ['پیام‌های ورودی', summary.inbound, ArrowRight], ['لیدهای متصل', summary.leads, Target], ['اجراهای اتوماسیون', summary.automation_runs, Zap]] as const; return <div className="flex flex-col gap-6"><div><Link href="/admin/instagram" className="inline-flex items-center gap-2 text-xs font-bold text-navy/50 hover:text-brand-700"><ArrowRight className="size-4" /> بازگشت به Inbox</Link><h1 className="mt-3 text-2xl font-black text-navy">تحلیل عملکرد اینستاگرام</h1><p className="mt-2 text-sm text-navy/50">نمای کلی تعاملات ثبت‌شده در سیستم و تبدیل آن‌ها به لید CRM.</p></div>
        <InstagramGuide
            title="اعداد این صفحه چه می‌گویند؟"
            steps={[
                { title: 'کارت‌های بالای صفحه', text: 'گفتگوها = تعداد مخاطبان یکتا؛ پیام‌های ورودی = پیام‌هایی که کاربر فرستاده؛ لیدهای متصل = گفتگوهایی که به مخاطب CRM وصل شده‌اند.' },
                { title: 'تفکیک کانال', text: 'نسبت دایرکت به کامنت نشان می‌دهد مخاطبان بیشتر خصوصی پیام می‌دهند یا زیر پست‌ها نظر می‌گذارند؛ اگر کامنت زیاد است، پاسخ عمومی + اتوماسیون کامنت اثرگذارتر است.' },
                { title: 'نمودار ۳۰ روز اخیر', text: 'طول هر نوار تعداد پیام‌های آن روز است؛ افت ناگهانی بعد از تغییر تنظیمات متا معمولاً یعنی Webhook قطع شده است.' },
                { title: 'اجراهای اتوماسیون', text: 'تعداد دفعاتی که پاسخ‌های خودکار ارسال شده‌اند؛ اگر صفر است با اینکه قانون دارید، بخش تاریخچه اجراها در صفحه اتوماسیون را بررسی کنید.' },
            ]}
            hints={[
                'این آمار فقط تعاملات ثبت‌شده در سایت است و با Insights رسمی اینستاگرام (ایمپرشن، ریچ) یکی نیست.',
            ]}
        /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label, value, Icon]) => <div key={label} className="flex items-center gap-3 rounded-2xl bg-white p-4 shadow-soft ring-1 ring-navy/5"><Icon className="size-5 text-brand-600" /><div><strong className="block text-xl font-black text-navy">{value}</strong><span className="text-xs font-bold text-navy/45">{label}</span></div></div>)}</section><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl bg-white p-6 shadow-soft ring-1 ring-navy/5"><div className="flex items-center gap-2 text-sm font-black text-navy"><BarChart3 className="size-5 text-brand-600" /> تفکیک کانال</div><div className="mt-5 space-y-4">{Object.entries(byChannel).map(([key, value]) => <div key={key}><div className="mb-1 flex justify-between text-xs font-black text-navy"><span>{key === 'comment' ? 'کامنت' : 'دایرکت'}</span><span>{value}</span></div><div className="h-2 overflow-hidden rounded-full bg-brand-100"><span className="block h-full rounded-full bg-brand-500" style={{ width: `${Math.min(100, (value / Math.max(1, summary.conversations)) * 100)}%` }} /></div></div>)}{Object.keys(byChannel).length === 0 && <p className="text-xs font-bold text-navy/45">داده‌ای ثبت نشده است.</p>}</div></div><div className="rounded-2xl bg-white p-6 shadow-soft ring-1 ring-navy/5"><div className="text-sm font-black text-navy">فعالیت ۳۰ روز اخیر</div><div className="mt-5 space-y-2">{byDay.map((item) => <div key={item.day} className="flex items-center gap-3 text-xs"><code dir="ltr" className="w-24 text-navy/45">{item.day}</code><div className="h-2 flex-1 overflow-hidden rounded-full bg-brand-100"><span className="block h-full rounded-full bg-deep-green" style={{ width: `${Math.min(100, item.total * 10)}%` }} /></div><strong className="w-8 text-left text-navy">{item.total}</strong></div>)}{byDay.length === 0 && <p className="text-xs font-bold text-navy/45">هنوز فعالیتی در ۳۰ روز اخیر ثبت نشده است.</p>}</div></div></section></div>; }
InstagramAnalytics.layout = (page: ReactNode) => <AdminLayout title="تحلیل Instagram">{page}</AdminLayout>;
